# Project's GitLab CI configuration

# Use the global node.js docker image
image: node

# Global Vars
variables:
  PKG_NAME: "theme"

# Global Caching rules, enabled per-ref caching
cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - assets/vendor/

# First install bower and gulp-cli globally and then
# install/require all dependencies
before_script:
  - yarn install
  - export PATH=$(yarn bin):$PATH
  - bower install --allow-root

stages:
  - lint
  - build

lint:all:
  stage: lint
  script: NODE_ENV=production gulp lint

build:all:
  stage: build
  only:
   - master
  script:
    - NODE_ENV=production gulp build
  artifacts:
    name: "${PKG_NAME}_${CI_BUILD_REF}"
    paths:
      - dist/
      - assets/
      - ./*.html
      - humans.txt
      - LICENSE