# Project's Travis CI configuration

# Use node.js image
language: node_js

# Global Caching
cache:
  directories:
    - node_modules/
    - assets/vendor/

# First install bower and gulp-cli globally and then
# install/require all dependencies
before_script:
  - yarn install
  - export PATH=$(yarn bin):$PATH
  - bower install --allow-root

# Define whitelist
branches:
  only:
     - master

# Compile files
script:
    - NODE_ENV=production gulp compile

# Build artifacts
# uncomment the following lines to deploy artifacts
# be sure to set environment variables for aws
# see more here: https://docs.travis-ci.com/user/uploading-artifacts/
# addons:
#  artifacts:
#    paths:
#      - dist/
#      - assets/vendor/
#      - ./*.html
#      - humans.txt
#      - LICENSE